[package]
name = "armes_cpu_wasm"
version = "0.1.0"
authors = ["theperkinrex <theperkinrex@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.6"
toml = "0.5.0"
armes_cpu_lib = { path = "../armes_cpu_lib" }

[lib]
crate-type = ["cdylib", "rlib"]